package com.cwcontest

import android.content.ContentValues
import android.content.Context
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

/**
 * LogManager
 *
 * In-memory QSO log with ADIF / CSV export and crash-safe persistence.
 *
 * Every logged QSO is appended to an ADIF file in the app's private external
 * documents folder, and that file is re-parsed on startup so the log survives
 * app restarts and device reboots.
 *
 * Export targets:
 *  - Android 10 (API 29) and newer → MediaStore Downloads (no permission needed)
 *  - Android 8/9 (API 26-28)      → public Downloads (WRITE_EXTERNAL_STORAGE)
 *  - Anything else                → app-private documents folder
 */
class LogManager(private val context: Context) {

    private val _entries = mutableListOf<QSOEntry>()
    val entries: List<QSOEntry> get() = _entries.toList()

    private val utcFmt = SimpleDateFormat("HHmmss", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }
    private val dateFmt = SimpleDateFormat("yyyyMMdd", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }
    private val stampFmt = SimpleDateFormat("yyyyMMddHHmmss", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }

    init {
        loadPersisted()
    }

    // ── Add / Remove ─────────────────────────────────────────────────────────

    fun addQSO(entry: QSOEntry) {
        _entries.add(0, entry)   // newest first for RecyclerView
        appendAdifLine(entry)
    }

    fun removeQSO(id: Long) {
        _entries.removeAll { it.id == id }
        rewriteAdifFile()
    }

    fun isDupe(callsign: String, band: Band, mode: ContestMode): Boolean =
        callsign.isNotBlank() && _entries.any {
            it.callsign.uppercase() == callsign.uppercase() &&
            it.band == band &&
            it.contestMode == mode
        }

    fun clear() {
        _entries.clear()
        adifFile()?.delete()
    }

    fun count() = _entries.size

    // ── ADIF helpers ─────────────────────────────────────────────────────────

    private fun adifFile(): File? {
        val dir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS) ?: return null
        if (!dir.exists()) dir.mkdirs()
        return File(dir, "cwcontest_log.adi")
    }

    private fun adifField(tag: String, value: String) = "<$tag:${value.length}>$value"

    private fun entryToAdif(e: QSOEntry): String {
        val sb = StringBuilder()
        sb.append(adifField("QSO_DATE",   dateFmt.format(e.timestamp)))
        sb.append(adifField("TIME_ON",    utcFmt.format(e.timestamp)))
        sb.append(adifField("CALL",       e.callsign))
        sb.append(adifField("BAND",       bandToAdif(e.band)))
        // Locale.US: a German/Chinese locale must not turn "14.0250" into "14,0250"
        sb.append(adifField("FREQ",       String.format(Locale.US, "%.4f", e.frequency)))
        sb.append(adifField("MODE",       "CW"))
        sb.append(adifField("RST_SENT",   "599"))
        sb.append(adifField("RST_RCVD",   "599"))
        sb.append(adifField("STX_STRING", e.sentExchange))
        sb.append(adifField("SRX_STRING", e.rcvdExchange))
        sb.append(adifField("CONTEST_ID", e.contestMode.shortName))
        if (e.serialNumber != null) {
            sb.append(adifField("STX", "%03d".format(e.serialNumber)))
        }
        if (e.notes.isNotEmpty()) {
            sb.append(adifField("NOTES", e.notes))
        }
        sb.append("<EOR>\n")
        return sb.toString()
    }

    private fun bandToAdif(band: Band): String = when (band) {
        Band.BAND_160 -> "160M"
        Band.BAND_80  -> "80M"
        Band.BAND_40  -> "40M"
        Band.BAND_20  -> "20M"
        Band.BAND_15  -> "15M"
        Band.BAND_10  -> "10M"
        Band.BAND_6   -> "6M"
        Band.BAND_2   -> "2M"
        Band.BAND_70  -> "70CM"
    }

    private fun bandFromAdif(value: String): Band? = when (value.uppercase()) {
        "160M" -> Band.BAND_160
        "80M"  -> Band.BAND_80
        "40M"  -> Band.BAND_40
        "20M"  -> Band.BAND_20
        "15M"  -> Band.BAND_15
        "10M"  -> Band.BAND_10
        "6M"   -> Band.BAND_6
        "2M"   -> Band.BAND_2
        "70CM" -> Band.BAND_70
        else   -> null
    }

    private fun modeFromAdif(value: String?): ContestMode =
        ContestMode.values().firstOrNull { it.shortName.equals(value ?: "", true) }
            ?: ContestMode.CQ_WW_CW

    private fun appendAdifLine(entry: QSOEntry) {
        runCatching {
            val f = adifFile() ?: return
            if (!f.exists()) {
                f.writeText("Generated by CWContest for Android\n<EOH>\n")
            }
            f.appendText(entryToAdif(entry))
        }
    }

    private fun rewriteAdifFile() {
        runCatching {
            val f = adifFile() ?: return
            f.writeText("Generated by CWContest for Android\n<EOH>\n")
            _entries.reversed().forEach { f.appendText(entryToAdif(it)) }
        }
    }

    /** Parse the persisted ADIF file (best effort – never throws) */
    private fun loadPersisted() {
        val f = adifFile() ?: return
        if (!f.exists()) return
        val text = runCatching { f.readText() }.getOrNull() ?: return

        val records = mutableListOf<Map<String, String>>()
        var current = mutableMapOf<String, String>()
        val tag = Regex("<([A-Za-z_0-9]+)(?::(\\d+))?>")
        var i = 0
        while (i < text.length) {
            val m = tag.find(text, i) ?: break
            val name = m.groupValues[1].uppercase()
            val len  = m.groupValues[2].toIntOrNull()
            i = m.range.last + 1
            when {
                name == "EOH" -> { /* header end */ }
                name == "EOR" -> { records.add(current); current = mutableMapOf() }
                len != null && len > 0 && i + len <= text.length -> {
                    current[name] = text.substring(i, i + len)
                    i += len
                }
            }
        }
        if (current.isNotEmpty()) records.add(current)

        records.forEachIndexed { idx, r ->
            val call = r["CALL"] ?: return@forEachIndexed
            val band = bandFromAdif(r["BAND"] ?: "") ?: return@forEachIndexed
            val ts = runCatching {
                stampFmt.parse("${r["QSO_DATE"] ?: ""}${r["TIME_ON"] ?: "000000"}")
            }.getOrNull() ?: Date()
            _entries.add(
                QSOEntry(
                    id           = ts.time * 1000 + idx,
                    timestamp    = ts,
                    callsign     = call,
                    sentExchange = r["STX_STRING"] ?: "",
                    rcvdExchange = r["SRX_STRING"] ?: "",
                    band         = band,
                    frequency    = r["FREQ"]?.toDoubleOrNull() ?: band.mhz,
                    contestMode  = modeFromAdif(r["CONTEST_ID"]),
                    serialNumber = r["STX"]?.trim()?.toIntOrNull(),
                    notes        = r["NOTES"] ?: ""
                )
            )
        }
        // The file is oldest-first; the UI wants newest-first.
        _entries.reverse()
    }

    // ── Export ───────────────────────────────────────────────────────────────

    /** Full log as an ADIF string */
    fun exportAdif(): String {
        val sb = StringBuilder()
        sb.append("Generated by CWContest for Android\n")
        sb.append(adifField("PROGRAMID", "CWContest")).append('\n')
        sb.append(adifField("PROGRAMVERSION", "1.1.0")).append('\n')
        sb.append("<EOH>\n\n")
        _entries.reversed().forEach { sb.append(entryToAdif(it)).append('\n') }
        return sb.toString()
    }

    /** Full log as a CSV string */
    fun exportCsv(): String {
        val sb = StringBuilder()
        sb.append("Date,Time(UTC),Callsign,Band,Freq(MHz),SentExch,RcvdExch,Contest,Serial,Macro\n")
        _entries.reversed().forEach { e ->
            sb.append("${dateFmt.format(e.timestamp)},")
            sb.append("${utcFmt.format(e.timestamp)},")
            sb.append("${csv(e.callsign)},")
            sb.append("${e.band.displayName},")
            sb.append("${String.format(Locale.US, "%.4f", e.frequency)},")
            sb.append("${csv(e.sentExchange)},")
            sb.append("${csv(e.rcvdExchange)},")
            sb.append("${e.contestMode.shortName},")
            sb.append("${e.serialNumber ?: ""},")
            sb.append("${csv(e.notes)}\n")
        }
        return sb.toString()
    }

    private fun csv(value: String) = "\"${value.replace("\"", "\"\"")}\""

    /** Write the log somewhere the user can reach, return a readable path */
    fun saveAdifToDownloads(filename: String? = null): String? =
        writeFile(filename ?: "cwcontest_${dateFmt.format(Date())}.adi",
                  "text/plain", exportAdif())

    fun saveCsvToDownloads(filename: String? = null): String? =
        writeFile(filename ?: "cwcontest_${dateFmt.format(Date())}.csv",
                  "text/csv", exportCsv())

    private fun writeFile(name: String, mime: String, content: String): String? {
        val bytes = content.toByteArray(Charsets.UTF_8)

        // API 29+: MediaStore Downloads, no runtime permission required.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            var result: String? = null
            runCatching {
                val resolver = context.contentResolver
                val values = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, name)
                    put(MediaStore.MediaColumns.MIME_TYPE, mime)
                    put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                    put(MediaStore.MediaColumns.IS_PENDING, 1)
                }
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values)
                if (uri != null) {
                    resolver.openOutputStream(uri)?.use { it.write(bytes) }
                    values.clear()
                    values.put(MediaStore.MediaColumns.IS_PENDING, 0)
                    resolver.update(uri, values, null, null)
                    result = "Download/$name"
                }
            }
            if (result != null) return result
        } else {
            var legacy: String? = null
            runCatching {
                val dir = Environment
                    .getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                if (dir.exists() || dir.mkdirs()) {
                    val f = File(dir, name)
                    f.writeBytes(bytes)
                    legacy = f.absolutePath
                }
            }
            if (legacy != null) return legacy
        }

        // Last resort: app-private folder (always writable).
        var fallback: String? = null
        runCatching {
            val dir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS) ?: return@runCatching
            if (!dir.exists()) dir.mkdirs()
            val f = File(dir, name)
            f.writeBytes(bytes)
            fallback = f.absolutePath
        }
        return fallback
    }
}
